name: Reclutamineto de villanos

on: push

jobs:
  reporte-de-reclutamiento:
    runs-on: ubuntu-latest

    steps:
      - name: CEl ajente se presneta
        run:
          echo "Soy el lider de la generacion del mal"

      - name: CEl ajente se presneta
        run: |
          echo "Soy el lider de la generacion del mal"
          echo "***************************"
          echo "Mi objetivo es conquistar el mundo"
          echo "Nombre clave: ${{ github.actor }}"
          echo ""
          echo "Contexto de Github: "
          echo "Repositorio: ${{ github.repository }}"
          echo "Operacion: ${{ github.sha }}"
          echo "Metadata: ${{ toJSON(github) }}"


      - name: Capacidad del agente 
        run: |
            echo "Mi capacidad de reclutamiento es alta"
            echo "Puedo reclutar a cualquier persona con habilidades especiales"
            uname -a
            node --version
            git --version
            echo "Mi equipo de villanos es fuerte y leal"

