name: Acceso a la fortaleza

on: push

jobs:
  acceso-a-la-base:
    runs-on: ubuntu-latest

    steps:
      - name:El ajente llega a la fortaleza
        run: |
        echo "Agente: ${{ github.actor }} ha llegado a la fortaleza"
        echo ""
        ls -la 
