name: Comunicador de la legion del mal

on:
  workflow_dispatch:
    inputs:
      villano:
        description: "¿Que villano envia el mensaje?"
        required: true
        tipee: choices
        options:
          - "Dr. Maligno"
          - "El villano de la semana"
          - "El lider de la generacion del mal"
      mensaje:
        description: "Mensaje a enviar"
        required: true
        type: string

      prioridad:
        description: "Nivel de prioridad"
        required: true
        type: choice
        options:
          - "Alta"
          - "Media"
          - "Baja"

jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest


    steps:
       - name: Imprimir inputs
          run: |
            echo "Inputs"
            echo "Villanos ${{inputs.villano}}"
            echo "Nivel de prioridad ${{inputs.prioridad}}"
            echo "Mensaje ${{inputs.mensaje}}"
